### ISSUE TITLE
Should we merge lists?

### ISSUE THREAD

**Issue by jorgtied** [asivokon/awesome-ukrainian-nlp#4]
Nice list of Ukrainian NLP tools and resources. I also started to collect one and I wonder whether we should merge (or at least link to each other)? https://github.com/Helsinki-NLP/UkrainianLT/

**Comment by osyvokon** [comment]
Hey @jorgtied, thanks for your amazing work! 

I guess it makes sense to keep both lists as they have different selection bias. Yours is obviously much more complete in terms of MT, for example.

I've stolen some links from it and referenced it in few places. Feel free to take any parts of this list as well. 💙💛
