### ISSUE TITLE
[Question] POS Tagger for Ukrainian language

### ISSUE THREAD

**Issue by cidrugHug8** [asivokon/awesome-ukrainian-nlp#5]
Hi.

I intend to create a natural language processing tool for Ukrainian. I am looking for POS Tagger for Ukrainian language. Could you please let me know if you have any recommendations for a Tagger?

Thank you.

**Comment by osyvokon** [comment]
Hi @cidrugHug8,

One option is to use [Stanza](https://stanfordnlp.github.io/stanza/pos.html). For example:

```python
import stanza
stanza.download("uk")
nlp = stanza.Pipeline("uk")
[w.upos for w in nlp("На дереві висить червоне яблуко смачне").sentences[0].words]

# Output: ['ADP', 'NOUN', 'VERB', 'ADJ', 'NOUN', 'ADJ']
```

**Comment by cidrugHug8** [comment]
Thank you. I'll give it a try.
